name: Sanity build tests
on: push
jobs:
  AdditionalLease-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:Additionallease
          browser: firefox
          
      - name: Cypress test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Mochaawesome Test Report
          path: cypress/reports/html
  # All-run:
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     # Install npm dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v6
  #       with:
  #         browser: firefox













